name: Build and deploy React App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
        
      - name: Install dependencies and build project
        run: | 
          npm ci
          npm run build --if-present
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: SSH-KEY
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: unnecessary
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: rsync -avz . -e "ssh -i $HOME/.ssh/id_rsa" root@${{ secrets.SSH_HOST }}:/var/www/digitalvixen/
